apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prince-acro-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/XXRadeonXFX/acro-cd-demo.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: prince-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
